//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class AdminLogin
{
    protected global::System.Web.UI.WebControls.TextBox txtUser;
    protected global::System.Web.UI.WebControls.TextBox txtPass;
    protected global::System.Web.UI.WebControls.CheckBox chkRemember;
    protected global::System.Web.UI.WebControls.Button btnLogin;
    protected global::System.Web.UI.WebControls.Label lblStatus;
}
