//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 4.0
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class AdminMemberships
{
    /// <summary>
    /// gvMemberships control.
    /// </summary>
    protected GridView gvMemberships;

    /// <summary>
    /// lblAdminStatus control.
    /// </summary>
    protected Label lblAdminStatus;
}
