//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 4.0
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class Membership
{
    /// <summary>
    /// txtFullName control.
    /// </summary>
    protected TextBox txtFullName;

    /// <summary>
    /// ddlMemberType control.
    /// </summary>
    protected DropDownList ddlMemberType;

    /// <summary>
    /// txtDepartment control.
    /// </summary>
    protected TextBox txtDepartment;

    /// <summary>
    /// txtRollId control.
    /// </summary>
    protected TextBox txtRollId;

    /// <summary>
    /// txtBatch control.
    /// </summary>
    protected TextBox txtBatch;

    /// <summary>
    /// txtMailbox control.
    /// </summary>
    protected TextBox txtMailbox;

    /// <summary>
    /// txtPhoneNumber control.
    /// </summary>
    protected TextBox txtPhoneNumber;

    /// <summary>
    /// ddlPassport control.
    /// </summary>
    protected DropDownList ddlPassport;

    /// <summary>
    /// txtMessage control.
    /// </summary>
    protected TextBox txtMessage;

    /// <summary>
    /// btnSubmit control.
    /// </summary>
    protected Button btnSubmit;

    /// <summary>
    /// lblStatus control.
    /// </summary>
    protected Label lblStatus;
}
